"""Fold the eval500_fb_nobc_cube_*.json ladder into docs/tables/fb_nobc_cube_ladder.md.

Reads $PSM_DATA/logs/eval500_<group>_<E>k_sd<S>.json (written by
scripts/baselines/fb_eval500.py) and prints one row per checkpoint: each seed's 500-episode
success, the across-seed mean +/- sd, and a final LATE row averaging 300k-500k over seeds.
Late window is 300k-500k, matching the affine-psi ladder this baseline sits beside.
"""
import argparse
import glob
import json
import os
import statistics as st

EPOCHS = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
LATE = [300, 350, 400, 450, 500]
# The affine-psi ladder in docs/tables/results.md reports its late mean over 250k-500k, so
# the same window is printed here too -- otherwise the two "late means" are not comparable.
LATE_ALT = [250, 300, 350, 400, 450, 500]


def load(logs, group):
    out = {}
    for p in glob.glob(os.path.join(logs, f"eval500_{group}_*k_sd*.json")):
        with open(p) as f:
            d = json.load(f)
        base = os.path.basename(p)[len(f"eval500_{group}_"):-len(".json")]
        ek, sd = base.split("_sd")
        out[(int(ek[:-1]), int(sd))] = d
    return out


def fmt(v, nd=3):
    return "--" if v is None else f"{v:.{nd}f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--logs", default=os.path.join(os.environ.get("PSM_DATA", ""), "logs"))
    ap.add_argument("--group", default="fb_nobc_cube")
    ap.add_argument("--seeds", default="0,1,2")
    ap.add_argument("--out", default="docs/tables/fb_nobc_cube_ladder.md")
    ap.add_argument("--title", default="Plain FB, BC anchoring off -- cube-single ladder")
    a = ap.parse_args()
    seeds = [int(s) for s in a.seeds.split(",")]
    rows = load(a.logs, a.group)

    lines = [f"# {a.title}", ""]
    lines.append("Generated by `scripts/baselines/fb_ladder_table.py`; do not hand-edit.")
    lines.append("")
    lines.append("| epoch | " + " | ".join(f"seed {s}" for s in seeds) + " | mean +/- sd |")
    lines.append("|---|" + "---|" * (len(seeds) + 1))
    per_seed_late = {s: [] for s in seeds}
    for e in EPOCHS:
        vals = []
        cells = []
        for s in seeds:
            d = rows.get((e, s))
            v = d["success"] if d else None
            cells.append(fmt(v))
            if v is not None:
                vals.append(v)
                if e in LATE:
                    per_seed_late[s].append(v)
        if vals:
            m = st.mean(vals)
            sd = st.stdev(vals) if len(vals) > 1 else 0.0
            agg = f"{m:.3f} +/- {sd:.3f}"
        else:
            agg = "--"
        lines.append(f"| {e}k | " + " | ".join(cells) + f" | {agg} |")

    def window(win):
        return [rows[(e, s)]["success"] for s in seeds for e in win if (e, s) in rows]

    flat = window(LATE)
    lines.append("")
    if flat:
        m, sd = st.mean(flat), (st.stdev(flat) if len(flat) > 1 else 0.0)
        ci = 1.96 * sd / (len(flat) ** 0.5)
        lines.append(f"**Late mean (300k-500k, {len(flat)} measurements): "
                     f"{m:.3f} +/- {ci:.3f}** (sd {sd:.3f}, "
                     f"min {min(flat):.3f}, max {max(flat):.3f})")
        for s in seeds:
            if per_seed_late[s]:
                lines.append(f"- seed {s} late mean: {st.mean(per_seed_late[s]):.3f}")
        alt = window(LATE_ALT)
        if alt:
            m2, sd2 = st.mean(alt), (st.stdev(alt) if len(alt) > 1 else 0.0)
            ci2 = 1.96 * sd2 / (len(alt) ** 0.5)
            lines.append(f"- same statistic on the affine ladder's 250k-500k window "
                         f"({len(alt)} measurements): **{m2:.3f} +/- {ci2:.3f}**")
    else:
        lines.append("**Late mean: no measurements yet.**")

    txt = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, "w") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
