agent_name: iql
lr: 3e-4
batch_size: 256
actor_hidden_dims: [512, 512, 512, 512]
value_hidden_dims: [512, 512, 512, 512]
layer_norm: true
actor_layer_norm: false
discount: 0.99
tau: 0.005
expectile: 0.9
actor_loss: awr        # 'awr' or 'ddpgbc'
alpha: 10.0            # AWR temperature or DDPG+BC coefficient
const_std: true
encoder: null
