"""Zero-shot across the FIVE cube tasks: 500-episode success per OGBench task.

Why this exists. Every cube number this project has ever reported is OGBench **task 2**.
`cube-single-play-singletask-v0` carries no task token, and `cube_env.py` defaults
`reward_task_id` to 2; `utils/evaluation.py` never passes `options={'task_id': ...}`, so
the bare id was silently one of five tasks. (The mazes' bare default is task 1, so every
antmaze/pointmaze number is task 1.) The paper claims zero-shot transfer, which is a claim
about a *family* of reward functions, and one task cannot support it.

Nothing had to be retrained to fix that. `agents/psmflow.py` reads `batch['rewards']` only
in `infer_z`/`infer_eval_z` -- the eval-time closed-form task vector -- so the frozen flow,
phi, psi and the latent index are all reward-free. `ogbench.make_env_and_datasets` loads the
SAME `cube-single-play-v0.npz` for every task id and only relabels the rewards, so switching
`env_name` to `cube-single-play-singletask-task{K}-v0` gives each task its own inferred `w`
against one unchanged representation. That is the zero-shot protocol stated properly.

Series, per task K in 1..5:
  * affine PSMFlow -- `eval500_affine{N}k_strict_cube_task{K}_sd{S}.json` for K != 2 and
    `eval500_affine{N}k_strict_cube_sd{S}.json` for K = 2 (the pre-existing task-2 evals,
    same checkpoints, same protocol), restricted to the 300k-500k window.
  * BC control -- `evals/bc_cube_task{K}.json` (K != 2) / `evals/bc_cube.json` (K = 2), the
    frozen Stage-A flow acting alone on that task. Reward-free too, but the task changes
    what counts as success, so each task needs its own control.

Epoch comes from each JSON's `restore_epoch`; seed from the filename's `_sd<N>` suffix
(the JSON's `seed` is the EVAL seed -- reports written after 2026-09-06 also carry
`train_seed`, but the earlier task-2 batch does not).

Run:
    .venv/bin/python tools/fig_affine_multitask.py --logs $PSM_DATA/logs \
        --evals-dir $PSM_DATA/evals
"""
import argparse
import glob
import json
import os
import re
import statistics as st

import matplotlib

matplotlib.use('Agg')

import figstyle
import matplotlib.pyplot as plt
from fig_affine_learning_curve import _mean_ci, per_epoch_stats, pooled_window

TASKS = [1, 2, 3, 4, 5]
DEFAULT_TASK = 2  # what a bare `cube-single-play-singletask-v0` evaluates
WINDOW = (300000, 500000)
SD_RE = re.compile(r'_sd(\d+)\.json$')


def _cells(logs, task):
    """{(epoch, seed): {...}} for one task, restricted to the 300k-500k window."""
    pat = ('eval500_affine*strict_cube_sd*.json' if task == DEFAULT_TASK
           else f'eval500_affine*strict_cube_task{task}_sd*.json')
    best = {}
    for p in sorted(glob.glob(os.path.join(logs, pat))):
        base = os.path.basename(p)
        m = SD_RE.search(base)
        if not m:
            continue
        with open(p) as f:
            d = json.load(f)
        epoch = int(d['restore_epoch'])
        if not (WINDOW[0] <= epoch <= WINDOW[1]):
            continue
        key = (epoch, int(m.group(1)))
        mtime = os.path.getmtime(p)
        if key in best and best[key]['mtime'] >= mtime:
            continue
        best[key] = {'success': float(d['success']), 'num_success': d.get('num_success'),
                     'num_episodes': d.get('num_episodes'), 'env': d.get('env'),
                     'train_seed': d.get('train_seed'), 'json': base, 'mtime': mtime}
    return best


def _bc(evals_dir, task):
    name = 'bc_cube.json' if task == DEFAULT_TASK else f'bc_cube_task{task}.json'
    path = os.path.join(evals_dir, name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        d = json.load(f)
    return {'success': float(d['success']), 'wilson95': d.get('wilson95'),
            'env': d.get('env'), 'json': name}


def collect(logs, evals_dir):
    return {t: {'cells': _cells(logs, t), 'bc': _bc(evals_dir, t)} for t in TASKS}


def build_report(data):
    agg = {}
    for t in TASKS:
        cells = data[t]['cells']
        agg[t] = {'per_epoch': per_epoch_stats(cells),
                  'window': pooled_window(cells, *WINDOW)}
    means = [agg[t]['window']['mean'] for t in TASKS if agg[t]['window']]
    bcs = [data[t]['bc']['success'] for t in TASKS if data[t]['bc']]
    agg['average'] = {
        'n_tasks': len(means),
        'mean': (st.mean(means) if means else None),
        'half_width': (_mean_ci(means)[1] if len(means) > 1 else 0.0),
        'bc_n_tasks': len(bcs),
        'bc_mean': (st.mean(bcs) if bcs else None),
        'bc_half_width': (_mean_ci(bcs)[1] if len(bcs) > 1 else 0.0),
    }
    return agg


def write_table(data, agg, out_md):
    L = []
    L.append('# Zero-shot across the five cube tasks (affine PSMFlow, paper-strict)')
    L.append('')
    L.append('GENERATED by `tools/fig_affine_multitask.py`; do not hand-edit.')
    L.append('')
    L.append('One representation per seed, five reward functions inferred in closed form at')
    L.append('eval (`infer_eval_z`). No retraining: nothing in the training losses reads')
    L.append('rewards, and every task shares the same `cube-single-play-v0` dataset with only')
    L.append('the reward column relabelled (`ogbench.utils.relabel_dataset`).')
    L.append('')
    L.append('**Task 2 is the default.** `cube-single-play-singletask-v0` has no task token and')
    L.append('`cube_env.py` sets `reward_task_id=2`, so every cube number reported before')
    L.append('2026-09-06 -- headline, ladder, ablations -- is task 2 alone. (The maze envs')
    L.append('default to task 1, so every antmaze and pointmaze number is task 1.)')
    L.append('')
    L.append(f'Late mean pools every (checkpoint, seed) measurement in '
             f'{WINDOW[0] // 1000}k-{WINDOW[1] // 1000}k; ± is `1.96*std/sqrt(n)` over those')
    L.append('n measurements. BC control is the frozen Stage-A flow acting alone on that task.')
    L.append('')
    L.append('| task | n (ckpt x seed) | late mean 300k-500k ± 95% CI | BC control | ratio vs BC |')
    L.append('|---|---|---|---|---|')
    for t in TASKS:
        w = agg[t]['window']
        bc = data[t]['bc']
        if w is None:
            L.append(f'| task {t}{" (default)" if t == DEFAULT_TASK else ""} | 0 | -- | '
                     + ('--' if bc is None else f'{bc["success"]:.3f}') + ' | -- |')
            continue
        bc_s = '--' if bc is None else f'{bc["success"]:.3f}'
        ratio = ('--' if (bc is None or bc['success'] <= 0)
                 else f'{w["mean"] / bc["success"]:.1f}x')
        L.append(f'| task {t}{" (default)" if t == DEFAULT_TASK else ""} | {w["n"]} | '
                 f'{w["mean"]:.3f} ± {w["half_width"]:.3f} | {bc_s} | {ratio} |')
    a = agg['average']
    avg = '--' if a['mean'] is None else f"{a['mean']:.3f} ± {a['half_width']:.3f}"
    bavg = '--' if a['bc_mean'] is None else f"{a['bc_mean']:.3f} ± {a['bc_half_width']:.3f}"
    L.append(f"| **5-task average** | {a['n_tasks']} tasks | **{avg}** | **{bavg}** | " +
             ('--' if not a['bc_mean'] else f"**{a['mean'] / a['bc_mean']:.1f}x**") + ' |')
    L.append('')
    L.append('(The ± on the average is across the five task means, not across seeds.)')
    L.append('')
    L.append('## Per-checkpoint mean across seeds')
    L.append('')
    epochs = sorted({e for t in TASKS for e in agg[t]['per_epoch']})
    L.append('| epoch | ' + ' | '.join(f'task {t}' for t in TASKS) + ' |')
    L.append('|---' * (len(TASKS) + 1) + '|')
    for e in epochs:
        row = []
        for t in TASKS:
            s = agg[t]['per_epoch'].get(e)
            row.append('--' if s is None else f"{s['mean']:.3f} (n={s['n']})")
        L.append(f'| {e // 1000}k | ' + ' | '.join(row) + ' |')
    L.append('')
    L.append('| BC control | ' + ' | '.join(
        '--' if data[t]['bc'] is None else f"{data[t]['bc']['success']:.3f}" for t in TASKS)
        + ' |')
    L.append('')
    os.makedirs(os.path.dirname(out_md), exist_ok=True)
    with open(out_md, 'w') as f:
        f.write('\n'.join(L))
    print(f'wrote {out_md}')


def plot(data, agg, out_png):
    figstyle.use_style()
    fig, (ax, bx) = plt.subplots(1, 2, figsize=(12.0, 4.5),
                                 gridspec_kw={'width_ratios': [1.55, 1.0]})

    for i, t in enumerate(TASKS):
        color = figstyle.PALETTE[i % len(figstyle.PALETTE)]
        stats = agg[t]['per_epoch']
        epochs = sorted(stats)
        if epochs:
            xs = [e / 1000 for e in epochs]
            ys = [stats[e]['mean'] for e in epochs]
            lo = [stats[e]['mean'] - stats[e]['half_width'] for e in epochs]
            hi = [stats[e]['mean'] + stats[e]['half_width'] for e in epochs]
            ax.plot(xs, ys, lw=2.0, marker='o', markersize=4, color=color,
                    label=f'task {t}' + (' (default)' if t == DEFAULT_TASK else ''))
            ax.fill_between(xs, lo, hi, color=color, alpha=0.09, linewidth=0)
        bc = data[t]['bc']
        if bc is not None:
            ax.axhline(bc['success'], color=color, ls=':', lw=1.0, alpha=0.8)

    ax.plot([], [], ls=':', lw=1.0, color=figstyle.INK_MUTED, label='BC control (per task)')
    ax.set_xlabel('checkpoint (k steps)')
    ax.set_ylabel('success (500 episodes)')
    ax.set_ylim(0, 1.0)
    ax.set_title('cube-single-play, one representation, five inferred tasks')
    ax.legend(fontsize=6, loc='upper left', ncol=2)

    # Right panel: late mean vs BC, per task.
    xs = list(range(len(TASKS)))
    ours = [agg[t]['window']['mean'] if agg[t]['window'] else 0.0 for t in TASKS]
    errs = [agg[t]['window']['half_width'] if agg[t]['window'] else 0.0 for t in TASKS]
    bcs = [data[t]['bc']['success'] if data[t]['bc'] else 0.0 for t in TASKS]
    bx.bar([x - 0.19 for x in xs], ours, width=0.36, yerr=errs, capsize=2.5,
           color=figstyle.PALETTE[0], label='affine PSMFlow (300k-500k pooled)')
    bx.bar([x + 0.19 for x in xs], bcs, width=0.36, color=figstyle.INK_MUTED, alpha=0.65,
           label='BC control')
    a = agg['average']
    if a['mean'] is not None:
        bx.axhline(a['mean'], color=figstyle.PALETTE[0], ls='--', lw=1.1)
        bx.text(-0.45, a['mean'] + 0.014, f"5-task avg {a['mean']:.3f}",
                color=figstyle.PALETTE[0], fontsize=6.5, ha='left')
    if a['bc_mean'] is not None:
        bx.axhline(a['bc_mean'], color=figstyle.INK_MUTED, ls='--', lw=1.1)
        bx.text(-0.45, a['bc_mean'] + 0.014, f"BC avg {a['bc_mean']:.3f}",
                color=figstyle.INK_MUTED, fontsize=6.5, ha='left')
    bx.set_xticks(xs)
    bx.set_xticklabels([f'task {t}' + ('\n(default)' if t == DEFAULT_TASK else '')
                        for t in TASKS], fontsize=6.5)
    bx.set_ylabel('success (500 episodes)')
    bx.set_ylim(0, 1.0)
    bx.set_title('late mean (300k-500k) vs BC, per task')
    bx.legend(fontsize=6, loc='upper right')

    fig.suptitle('Zero-shot across the five cube tasks: every earlier cube number is task 2')
    fig.tight_layout()
    fig.savefig(out_png, dpi=150)
    print(f'wrote {out_png}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--logs', default='/mnt/home/amohan/psm-data/logs')
    ap.add_argument('--evals-dir', default='/mnt/home/amohan/psm-data/evals')
    ap.add_argument('--name', default='2026-09-06-affine-cube-multitask')
    ap.add_argument('--out-dir', default=None)
    ap.add_argument('--table', default='affine_cube_multitask.md')
    args = ap.parse_args()

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = args.out_dir or os.path.join(repo, 'docs', 'figures')
    os.makedirs(out_dir, exist_ok=True)

    data = collect(args.logs, args.evals_dir)
    agg = build_report(data)

    report = {
        'logs': args.logs, 'evals_dir': args.evals_dir,
        'window': list(WINDOW), 'default_task': DEFAULT_TASK,
        'note': ('every cube number reported before 2026-09-06 is OGBench task 2 (the bare '
                 'singletask id\'s default); the maze envs default to task 1. Training is '
                 'reward-free, so the same checkpoints evaluate zero-shot on all five tasks '
                 'by changing env_name alone.'),
        'cells': {str(t): {f'{e}_{s}': c for (e, s), c in data[t]['cells'].items()}
                  for t in TASKS},
        'bc_control': {str(t): data[t]['bc'] for t in TASKS},
        'aggregate': {str(t): {'per_epoch': {str(e): v for e, v in agg[t]['per_epoch'].items()},
                               'window_300k_500k': agg[t]['window']} for t in TASKS},
        'five_task_average': agg['average'],
    }
    out_json = os.path.join(out_dir, f'{args.name}.json')
    with open(out_json, 'w') as f:
        json.dump(report, f, indent=1)
    print(f'wrote {out_json}')

    plot(data, agg, os.path.join(out_dir, f'{args.name}.png'))
    write_table(data, agg, os.path.join(repo, 'docs', 'tables', args.table))


if __name__ == '__main__':
    main()
